// ignore_for_file: non_constant_identifier_names, constant_identifier_names

class Strings {
  static const String NAME_APP = 'ToDoon';
  static const String FOLDER_APP = 'todoon';
  static const String DATA_FILE = 'data.json';
  static const String SETTINGS_FILE = 'settings.json';
  late String Add;
  late String Add_Plan;
  late String Add_Task;
  late String Alert;
  late String Allow;
  late String Allow_Content;
  late String Allow_Notifications;
  late String Back;
  late String Cancel;
  late String Complete;
  late String Date;
  late String Delete_Plan;
  late String Delete_Sure;
  late String Delete_Task;
  late String Description;
  late String Detete;
  late String Dismiss_Plan;
  late String Dismiss_Sure;
  late String Dismiss_Task;
  late String Dismissed;
  late String Dont_Allow;
  late String Edit;
  late String Edit_Plan;
  late String Edit_Sure;
  late String Edit_Task;
  late String Name_Plan;
  late String New_Plan;
  late String New_Task;
  late String No_Plans;
  late String No_Tasks;
  late String Off;
  late String OK;
  late String On;
  late String Out_Of;
  late String Plan;
  late String Plan_Dismissed;
  late String Plans;
  late String Quick_Add_Plan;
  late String Quick_Add_Task;
  late String Refresh;
  late String Reminder;
  late String Search;
  late String Setting_Azure_Title;
  late String Setting_Bleed_Title;
  late String Setting_Colors_Title;
  late String Setting_Dark_Title;
  late String Setting_Language_Title;
  late String Setting_Light_Title;
  late String Setting_System_Title;
  late String Setting_Theme_Title;
  late String Settings_Title;
  late String Show_Menu;
  late String Task;
  late String Task_Dismissed;
  late String Tasks;
  late String Wrong;
}
